create database LOS_CONSTRAINT
USE LOS_CONSTRAINT

CREATE TABLE PERSONA (
	ID VARCHAR (5) PRIMARY KEY,
	NOMBRE VARCHAR (50) NOT NULL,
	APE_PAT VARCHAR (50) NOT NULL,
	APE_MAT VARCHAR (50),
	FEC_REG DATE NOT NULL --DEFAULT GETDATE()
)

ALTER TABLE PERSONA
	ADD CONSTRAINT DF_FECHA_REG DEFAULT GETDATE()
	FOR FEC_REG
	
CREATE TABLE CUENTA (
	idCUENTA NUMERIC NOT NULL,
	TIPO_CUENTA VARCHAR (50) NOT NULL,
	idCLIENTE VARCHAR (5)
)

ALTER TABLE CUENTA
	--ADD CONSTRAINT PK_idCUENTA PRIMARY KEY (idCUENTA)
	--ADD CONSTRAINT FK_idCLIENTE FOREIGN KEY (idCLIENTE) REFERENCES PERSONA(ID)
	ADD CONSTRAINT CK_idCUENTA CHECK(LEN(IDCUENTA)=16)





ALTER TABLE PERSONA
	ADD Edad numeric CHECK(Edad >= 18)



UPDATE PERSONA SET Edad = 22 WHERE ID = 13131


INSERT INTO PERSONA VALUES
('11111','TADEO','SMITH','YAÑES',DEFAULT),
('12121','PANCHO','FANTA',NULL,'11-11-95'),
('13131','PAOLA','GOMEZ','LARA',DEFAULT),
('14141','KASANDRA','MEZA',NULL,'09-09-24'),
('15151','VALSA','SALSA','LANSA',DEFAULT)

INSERT INTO PERSONA VALUES
('16161','POLLO','PONCE',NULL,'12-12-1999','22')

INSERT INTO CUENTA VALUES
('1231231231231231','DE AHORRO','12121'),
('4564564564564564','DEBITO','13131'),
('7897897897897897','DE AHORRO','11111')

SELECT * FROM PERSONA

SELECT * FROM CUENTA

SELECT NOMBRE,idCUENTA FROM PERSONA p JOIN CUENTA c on p.ID = c.idCLIENTE

--tabla PERSONA, permitir agregar edades para personas mayores de edad


CREATE PROCEDURE LISTADO_PERSONAS AS Select * from PERSONA GO;

EXEC LISTADO_PERSONAS




CREATE PROCEDURE SP_BUSQUEDA_NOMBRE @EDADES NUMERIC 
AS 
select * from PERSONA WHERE EDAD = @EDADES 

EXEC SP_BUSQUEDA_NOMBRE @EDADES = 22




create procedure SP_AgregarPersona
@ID varchar(5),@Nombre varchar(50),@ApellidoPat varchar(50),@ApellidoMat varchar(50),@FechaReg date, @Edad numeric
as
begin
	insert into PERSONA values (@ID,@Nombre,@ApellidoPat,@ApellidoMat,@FechaReg,@Edad)
	
end

go;

EXEC SP_AgregarPersona @ID='19191', @Nombre='PAOLA', @ApellidoPat='GOMEZ', @ApellidoMat='LARA', @FechaReg='2019-05-08', @Edad=22


CREATE PROCEDURE SP_ACTUALIZAR
@id varchar(5), @NOMBRES varchar(50)
AS BEGIN
SELECT ID, NOMBRE FROM PERSONA WHERE ID = @id
Update PERSONA set NOMBRE = @NOMBRES WHERE ID=@id
SELECT ID, NOMBRE FROM PERSONA WHERE ID = @id
END

EXEC SP_ACTUALIZAR @id = '12121', @NOMBRES = 'LOMECAN'



create procedure SP_BORRAR
@id varchar(5)
as begin
delete FROM PERSONA where ID = @id
end

EXEC SP_BORRAR @idCliente = '11111'

create procedure SP_BORRAR_TODO
@id varchar(5)
as begin 
delete from PERSONA WHERE ID = @id
end

exec SP_BORRAR_TODO @id = '11111'